import type { VercelRequest, VercelResponse } from '@vercel/node';
import { createClient } from '@supabase/supabase-js';

// ─── ENVIRONMENT ───────────────────────────────────────────────────────────────
const SUPABASE_URL = process.env.SUPABASE_URL!;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;
const APIFY_API_KEY = process.env.APIFY_API_KEY ?? '';
const APIFY_ACTOR_ID = 'streamers~youtube-scraper';

const getSupabase = () => createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

// ─── VIDEO ID PARSING ─────────────────────────────────────────────────────────

function extractVideoId(url: string): string | null {
  const patterns = [
    /youtube\.com\/watch\?v=([\w-]{11})/,
    /youtu\.be\/([\w-]{11})/,
    /youtube\.com\/embed\/([\w-]{11})/,
    /youtube\.com\/shorts\/([\w-]{11})/,
    /^([\w-]{11})$/,
  ];
  for (const pattern of patterns) {
    const match = url.trim().match(pattern);
    if (match?.[1]) return match[1];
  }
  return null;
}

// ─── TRANSCRIPT FORMATTING ────────────────────────────────────────────────────

function formatTranscriptText(text: string): string {
  const sentences = text.match(/[^.!?]+[.!?]+/g) ?? [text];
  const paragraphs: string[] = [];
  const SENTENCES_PER_PARAGRAPH = 7;
  for (let i = 0; i < sentences.length; i += SENTENCES_PER_PARAGRAPH) {
    const para = sentences.slice(i, i + SENTENCES_PER_PARAGRAPH).join('').trim();
    if (para) paragraphs.push(para);
  }
  return paragraphs.length > 1 ? paragraphs.join('\n\n') : text;
}

// ─── APIFY TRANSCRIPT FETCH ───────────────────────────────────────────────────

async function fetchTranscript(
  _videoId: string,
  videoUrl: string
): Promise<{ transcript: string | null; language: string | null }> {
  if (!APIFY_API_KEY) return { transcript: null, language: null };
  try {
    const startResponse = await fetch(
      `https://api.apify.com/v2/acts/${APIFY_ACTOR_ID}/runs?token=${APIFY_API_KEY}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          startUrls: [{ url: videoUrl }],
          maxResults: 1,
          maxResultsShorts: 0,
          maxResultStreams: 0,
          downloadSubtitles: true,
          subtitlesLanguage: 'en',
          preferAutoGeneratedSubtitles: true,
          subtitlesFormat: 'plaintext',
        }),
        signal: AbortSignal.timeout(15000),
      }
    );
    if (!startResponse.ok) return { transcript: null, language: null };

    const startData = await startResponse.json() as {
      data?: { id?: string; defaultDatasetId?: string };
    };
    const runId = startData.data?.id;
    const datasetId = startData.data?.defaultDatasetId;
    if (!runId) return { transcript: null, language: null };

    const pollStart = Date.now();
    while (Date.now() - pollStart < 50_000) {
      await new Promise(resolve => setTimeout(resolve, 5000));
      const statusResponse = await fetch(
        `https://api.apify.com/v2/actor-runs/${runId}?token=${APIFY_API_KEY}`,
        { signal: AbortSignal.timeout(10000) }
      );
      if (!statusResponse.ok) continue;
      const statusData = await statusResponse.json() as { data?: { status?: string } };
      const status = statusData.data?.status;
      if (status === 'SUCCEEDED') {
        const resultsResponse = await fetch(
          `https://api.apify.com/v2/datasets/${datasetId}/items?token=${APIFY_API_KEY}`,
          { signal: AbortSignal.timeout(10000) }
        );
        if (!resultsResponse.ok) return { transcript: null, language: null };
        const items = await resultsResponse.json() as Array<{
          subtitles?: Array<{ plaintext?: string; language?: string }>;
        }>;
        const sub = items[0]?.subtitles?.[0];
        const raw = sub?.plaintext?.replace(/\s+/g, ' ').trim() || null;
        return {
          transcript: raw ? formatTranscriptText(raw) : null,
          language: sub?.language ?? 'en',
        };
      }
      if (['FAILED', 'ABORTED', 'TIMED-OUT'].includes(status ?? '')) {
        return { transcript: null, language: null };
      }
    }
    return { transcript: null, language: null };
  } catch {
    return { transcript: null, language: null };
  }
}

// ─── HANDLER ──────────────────────────────────────────────────────────────────

export default async function handler(req: VercelRequest, res: VercelResponse) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');

  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  // Verify user auth
  const auth = req.headers['authorization'];
  if (!auth?.startsWith('Bearer ')) return res.status(401).json({ error: 'Unauthorized' });

  const token = auth.slice(7);
  const supabase = getSupabase();

  try {
    const { data: { user } } = await supabase.auth.getUser(token);
    if (!user) return res.status(401).json({ error: 'Unauthorized' });
  } catch {
    return res.status(401).json({ error: 'Unauthorized' });
  }

  const { videoUrl } = req.body as { videoUrl?: string };
  if (!videoUrl) return res.status(400).json({ error: 'videoUrl is required' });

  const videoId = extractVideoId(videoUrl);
  if (!videoId) return res.status(400).json({ error: 'Invalid YouTube URL' });

  try {
    const { transcript, language } = await fetchTranscript(videoId, videoUrl);

    if (!transcript) {
      return res.status(422).json({
        error: 'No transcript available for this video. It may lack captions or be a live stream.',
      });
    }

    return res.status(200).json({ transcript, language, videoId });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error('[transcript] Error:', err);
    return res.status(500).json({ error: msg });
  }
}
